### ISSUE TITLE
Display Names 

### ISSUE THREAD

**Issue by RawrUniversal** [kacgal/ForgeSkype#2]
It seems display names don't work right. It doesn't display anyway even if they have a display name.

**Comment by kacgal** [comment]
Weird, they work fine for me. Which command did you try? Is there any error in the log?

**Comment by RawrUniversal** [comment]
No errors and i'm using "/ssm name message" with default config.

**Comment by kacgal** [comment]
Can you try v1.2.1? It should give an error message if it can't get the display name

**Comment by RawrUniversal** [comment]
Ok

**Comment by RawrUniversal** [comment]
[08:42:55] [AsyncSkypeMessageSender-1/INFO] [STDERR/forgeskype]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.StringIndexOutOfBoundsException: String index out of range: -35
[08:42:55] [AsyncSkypeMessageSender-1/INFO] [STDERR/forgeskype]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at java.lang.String.substring(Unknown Source)
[08:42:55] [AsyncSkypeMessageSender-1/INFO] [STDERR/forgeskype]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at com.skype.Chat.getUsersProperty(Chat.java:414)
[08:42:55] [AsyncSkypeMessageSender-1/INFO] [STDERR/forgeskype]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at com.skype.Chat.getAllMembers(Chat.java:340)
[08:42:55] [AsyncSkypeMessageSender-1/INFO] [STDERR/forgeskype]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at com.kacgal.forgeskype.ForgeSkype$1.chatMessageReceived(ForgeSkype.java:107)
[08:42:55] [AsyncSkypeMessageSender-1/INFO] [STDERR/forgeskype]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at com.skype.ChatMessageConnectorListener.fireMessageReceived(ChatMessageConnectorListener.java:76)
[08:42:55] [AsyncSkypeMessageSender-1/INFO] [STDERR/forgeskype]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at com.skype.ChatMessageConnectorListener.messageReceived(ChatMessageConnectorListener.java:51)
[08:42:55] [AsyncSkypeMessageSender-1/INFO] [STDERR/forgeskype]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at com.skype.connector.Connector.fireMessageEvent(Connector.java:1160)
[08:42:55] [AsyncSkypeMessageSender-1/INFO] [STDERR/forgeskype]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at com.skype.connector.Connector.access$500(Connector.java:37)
[08:42:55] [AsyncSkypeMessageSender-1/INFO] [STDERR/forgeskype]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at com.skype.connector.Connector$13.run(Connector.java:1139)
[08:42:55] [AsyncSkypeMessageSender-1/INFO] [STDERR/forgeskype]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[08:42:55] [AsyncSkypeMessageSender-1/INFO] [STDERR/forgeskype]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[08:42:55] [AsyncSkypeMessageSender-1/INFO] [STDERR/forgeskype]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at java.lang.Thread.run(Unknown Source)

**Comment by RawrUniversal** [comment]
Also, Can you add a reply option for "/ssm". Like if you don't put a skype name for it, it will reply to the person who messaged you last or a new command for that.

**Comment by kacgal** [comment]
Sure thing. I think I'm going to make a new command for that, just if you'd want to put someone's name as the first word in your reply, or do it by accident.
As to the error, it seems like it's a bug in the Skype API I'm using (taksan/skype-java-api#24), are you on a mac by any chance?

**Comment by RawrUniversal** [comment]
Nope. Windows 7.

**Comment by kacgal** [comment]
Are you running the latest Skype version? Check in Help -> Check for Updates

**Comment by RawrUniversal** [comment]
Yes, i am running the latest one.

**Comment by RawrUniversal** [comment]
i got this too. http://pastebin.com/npmU47GN

**Comment by kacgal** [comment]
I don't seem to be able to reproduce either of the errors, or see anything that could cause them. My guess would be that it's an error in your Skype, but I'm not sure.

**Comment by RawrUniversal** [comment]
ok :/

**Comment by RawrUniversal** [comment]
i got this on startup: http://pastebin.com/vqmZq50L

**Comment by kacgal** [comment]
Check if Java is allowed to connect to Skype (Tools -> Options -> Advanced -> Advanced settings -> Manage other programs' access to Skype)
On startup Skype might also ask you if you want to put it in silent mode, accept or deny that aswell

**Comment by RawrUniversal** [comment]
It is. I tried removing it and readding. and it works sometimes. still no display names tho.

**Comment by kacgal** [comment]
Do you get a pop-up asking if you want to allow silent mode? Check the 'do not ask again' if you don't want that on every start-up
I also tried the mod on a different computer, and there display names weren't working either, so I might be able to find a fix for that. There is no error tho, so I don't know
Oh, and which java version is Minecraft running with? It might have something to do with that

**Comment by RawrUniversal** [comment]
i dont get the silent mode pop-up. I did do not ask again thing. Also im using java 1.8, i dont the exact one.

**Comment by RawrUniversal** [comment]
Ok, i think i know what happened. It only seems to work if I personally changed their skype display name, otherwise it doesnt work.

**Comment by RawrUniversal** [comment]
I think I fixed it. I was thinking of 'full name' not 'display name'

**Comment by kacgal** [comment]
Thanks for reporting this, should be working properly in 1.2.2
